[settings]
format = "png"
transparent = false
dim = [12.0, 4.0]
dpi = 600
layout = "compressed"

# cenplot draw -t examples/tracks_line_logscale.toml -c haplotype2-0000105 -d . -p1
[[tracks]]
title = "Coverage"
position = "relative"
type = "line"
proportion = 0.1
path = "examples/data/line/first.bed.gz"
options = { legend = true, label = "First", marker="o", markersize=2, linestyle="none", hide_x = false, color = "black", ymax=60, log_scale = true }

[[tracks]]
position = "overlap"
type = "line"
path = "examples/data/line/second.bed.gz"
options = { legend = true, label = "Second", marker="o", markersize=2, linestyle="none", hide_x = false, color = "red", ymax=60, log_scale = true }
