[settings]
title = "{chrom}"
format = "png"
transparent = false
dim = [16.0, 8.0]
axis_h_pad = 0.1
dpi = 600

[[tracks]]
position = "relative"
type = "selfident"
proportion = 0.5
path = "examples/data/self_ident_custom_scale/chr1_h1:86865001-102805000.bed.gz"
options = { legend = true, hide_x = false, invert = true, legend_asp_ratio = 1.0, colorscale = "examples/self_ident_custom_scale/custom_colorscale.tsv" }
